// The Worker's bindings, derived from wrangler.jsonc rather than restated
// here. `worker-configuration.d.ts` is generated by `npm run types` and
// declares the ambient `Cloudflare.Env`; re-exporting it under the name
// call sites already import keeps this module as the single place to look,
// without a hand-written copy that can drift from the real configuration.
//
// This previously WAS hand-written, specifically to work around the
// rate-limit binding's type name varying between workers-types versions.
// Generated types declare `RateLimit` directly, so that workaround is gone
// along with the drift risk it carried.
//
// Re-run `npm run types` after editing wrangler.jsonc. CI typechecks against
// the committed file, so a stale one surfaces as a type error rather than as
// a runtime surprise.
export type Env = Cloudflare.Env;
